### ISSUE TITLE
Encoding of rules files does not seem to be used correctly

### ISSUE THREAD

**Issue by jensborrmann** [jQAssistant/jqa-commandline-tool#12]
Given:
- an Asciidoc rules file with German Umlauts (e.g. ü) with UTF-8-encoding
- OS: Windows 10

When:
- analyzing with command line runner

Then:
- the XML report (which is UTF-8 encoded) contains special stuff (e.g. '&Atilde;&frac14;' instead of 'ü')  

Is there any option that could be applied in order to change that behaviour, or is this a bug?

**Comment by obfischer** [comment]
Welcome to the UTF-8 Selbsthilfegruppe (https://twitter.com/theuer/status/117317444481187840?lang=de)

**Comment by obfischer** [comment]
This is quite nasty. Let me have a look at our tests and who difficult a possible might be.

**Comment by DirkMahler** [comment]
We need to verify if the problem occurs while reading the Asciidoc rules or writing the XML report (or both). That's part of the core framework, should "move" that issue that project.

**Comment by DirkMahler** [comment]
Asciidoc rule files are no longer supported by the jQA core, closing this issue.
